name: generative_ai_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.17.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  logging: ^1.2.0
  json_annotation: ^4.8.1
  mime: ^1.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mocktail: ^1.0.2
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  build_version: ^2.1.1
